package br.ufrn.imd.model.enums;

public enum Genre {
    ACTION, ADVENTURE, COMEDY, CRIME, DRAMA, FANTASY, HISTORICAL, HORROR, MYSTERY, PHILOSOPHICAL, POLITICAL, ROMANCE,
    SAGA, SATIRE, SCIENCE_FICTION, THRILLER, URBAN, WESTERN

}
